# Generated by Django 5.2.1 on 2025-09-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_uid', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('flutterwave', 'Flutterwave'), ('paypal', 'PayPal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('purpose', models.CharField(choices=[('assessment', 'Assessment Payment'), ('subscription', 'Subscription Payment'), ('consultation', 'Consultation Payment')], default='assessment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mpesa_checkout_request_id', models.CharField(blank=True, max_length=100)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('flutterwave_tx_ref', models.CharField(blank=True, max_length=100)),
                ('flutterwave_flw_ref', models.CharField(blank=True, max_length=100)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_uid', 'status'], name='payment_tra_user_ui_6dcc32_idx'), models.Index(fields=['payment_method', 'status'], name='payment_tra_payment_2e7662_idx'), models.Index(fields=['created_at'], name='payment_tra_created_e43546_idx')],
            },
        ),
    ]
