# Generated by Django 5.2.1 on 2025-09-30 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('flutterwave', 'Flutterwave')], max_length=20)),
                ('transaction_id', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'callback_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
