# Generated by Django 5.2.1 on 2025-09-30 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('payment', 'Payment Data'), ('user', 'User Data'), ('status', 'Status Update')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('user_uid', models.CharField(blank=True, max_length=128)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('data_synced', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'firebase_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
